AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
